### ISSUE TITLE
Zoom in for error-bars (plot package) not working properly.

### ISSUE THREAD

**Issue by encomer** [racket/plot#108]
In version 8.2 of DrRacket (installed with: racket-8.2-x86_64-win32-cs.exe)

Running the example code for **error-bars**, from the (**plot** _package_) documentation.
```
(require plot)
(plot (list (function sqr 1 7)
              (error-bars (list (vector 2 4 12)
                                (vector 4 16 20)
                                (vector 6 36 10)))))
```

When we use the option: "**click-and-drag to zoom**", _the error-bars zoom in correctly_, **only if we include in the zoom-window the center of the bar**, otherwise it is not included in the new window.

Specially when we work with multiple functions in the same graph, it would be very good to include the (partial) error-bars, even if we don't include the centers in the selected new window.

_Thank you for considering this issue_.
Best regards,

**Comment by alex-hhh** [comment]
Thanks for reporting this.  I have pushed a fix for this and will be available in the next Racket release (8.5)
