### ISSUE TITLE
Cannot show anything on Win10

### ISSUE THREAD

**Issue by Sophiamer2002** [racket/plot#122]
I ran the following three commands in racket REPL.
```racket
(require plot)
(plot-new-window? #t)
(plot (function sin (- pi) pi #:label "y = sin(x)")
```
However, the window just doesn't show anthing and is like the following figure 
![Picture1](https://github.com/racket/plot/assets/100857249/93e470e7-319b-4d72-ab45-eab52b29e01d)
I have no idea what the possible issue is. I guess it might be something wrong with my computer configuration. 

My racket environment:
Minimal Racket 8.9 Windows 64-bit x64
Only langserver package is downloaded through `raco pkg install racket-langserver` for magic racket usage in VS Code.

Any help is greatly appreciated.

**Comment by alex-hhh** [comment]
Hi @Sophiamer2002 , you mentioned that you installed Minimal Racket 8.9 and only installed the langserver package.  However, Minimal Racket does not contain the plot package, you either need to install the plot package explicitly, or install a full Racket distribution.

It is still not clear to me why the plot window appeared, as it should just reported that the plot package is not installed.  Are you sure you didn't install the plot package somehow?

**Comment by Sophiamer2002** [comment]
The result for `raco pkg show -a`:
```
Installation-wide:
 Package[*=auto]         Checksum           Source
 base*                   f318e23ec32859...  catalog base
 com-win32-x86_64*       073362d77940ae...  catalog...-x86_64
 db-win32-x86_64*        e8ee5c4957ff8d...  catalog...-x86_64
 racket-lib              9347cf1b6f8326...  catalog...ket-lib
 racket-win32-x86_64-3*  ead76dcfea3ac7...  catalog...86_64-3
User-specific for installation "8.9":
 Package[*=auto]               Checksum         Source
 [Some other packages]
 plot-compat*                  bc4f2449723f...  catalog...ompat
 plot-doc*                     697fafb35b26...  catalog...t-doc
 plot-gui-lib*                 8e3146289ea0...  catalog...i-lib
 plot-lib*                     b21397181340...  catalog...t-lib
 [Some other packages]
```
It should have been installed since when I run only (without setting plot-new-window which is by default false)
```
(require plot)
(plot (function sin (- pi) pi #:label "y = sin(x)"))
```
and it gives `(object:2d-plot-snip% ... ...)`, which I suppose that plot library is already installed.

**Comment by alex-hhh** [comment]
I am running Racket 8.9 myelf on Windows 11 and the plot library works without problems, so I am not sure what is happening in your case.  I have a few suggestions:

* Run the program in a terminal using racket.exe, and check if any errors are printed out in the terminal window when the empty plot window shows up - this might help diagnosing what is happening
* Install a full Racket distribution and try to run your program in DrRacket -- this would at least determine if the problem is with Racket and Windows, or there is something wrong in how you installed racket and the plot package.

**Comment by Sophiamer2002** [comment]
I have tried the first suggestion and the window appears with nothing showed. When I force close the window, the racket REPL just exit automatically without any error printed out. 

The second suggestion worked and no matter in DrRacket or in terminal, the plot is showed correctly. 
I found that on windows, there are several differences when using mininal version and full version:
+ The packages are installed at `C:\Users\Username\AppData\Roaming\Racket` and `C:\Program Files\Racket`, respectively.
+ Plot packages are automatically installed in full version and even when I ran `raco pkg install plot` in minimal racket, there is a subtle difference when listing packages related to plot library. 
  - When in minimal version, 
    ``` 
      plot                          797fda82ca47...  catalog plot
      plot-compat*                  bc4f2449723f...  catalog...ompat
      plot-doc*                     697fafb35b26...  catalog...t-doc
      plot-gui-lib*                 8e3146289ea0...  catalog...i-lib
      plot-lib*                     b21397181340...  catalog...t-lib
    ```  
  - While in full version, 
    ```
      plot*                         797fda82ca47...  catalog plot
      plot-compat*                  bc4f2449723f...  catalog...ompat
      plot-doc*                     697fafb35b26...  catalog...t-doc
      plot-gui-lib*                 8e3146289ea0...  catalog...i-lib
      plot-lib*                     b21397181340...  catalog...t-lib
    ```
  where an extra `*` is added after plot in full version.

I guess that there might be some packages missed in minimal version when installing plot by simply `raco pkg install plot`. Anyway, I found that using minimal racket is not that 'minimal' and I will use full version instead. Therefore, I will close this issue and thank @alex-hhh sincerely. 

By the way, I'm relatively new to programming languages. I found that learning a programming language in deep is quite hard by only reading books though I can command the basic usages. I would be appreciated if you could provide some advice into learning the whole picture of racket, by understanding more details in the language design.

**Comment by alex-hhh** [comment]
I am glad that you managed to get it working.

With regards to this:

> By the way, I'm relatively new to programming languages. I found that learning a programming language in deep is quite hard by only reading books though I can command the basic usages. I would be appreciated if you could provide some advice into learning the whole picture of racket, by understanding more details in the language design.

... I would recommend joining the racket community.  It is most active on Discourse (https://racket.discourse.group/ ) and Discord ( here is an invite link https://discord.gg/6Zq8sH5 )  You can ask questions there and get help and advice with learning Racket

**Comment by Sophiamer2002** [comment]
I really appreciate it. @alex-hhh
