### ISSUE TITLE
Add parameters to control printing tick points, axis lines.

### ISSUE THREAD

**Issue by sykora** [racket/plot#44]
Hi there,

In the vein #43, I'd love to have parameters to control the printing of tick points and axis lines (while keeping tick labels, unlike `[plot-x-axis? #f]` or `[plot-decorations #f]`.

I've identified the parts of the drawing code which would need to change --- `get-all-tick-params` and `draw-axes` in `plot-area`, but I don't seem to be able define the parameters in such a way that my main program can see them.

Can anyone help me fill in the gaps?

**Comment by alex-hhh** [comment]
Hi @sykora , unfortunately, it is not clear from your description what you are trying to achieve, and you have not provided any further details to my question.  There is also no code to look at, so I cannot help you.

I will close this issue now, but if you are still interested in it, please post a better description of what you are trying to do and also push your work in progress changes to your repository on Github so I can have a look.   I will than reopen this issue.
