### ISSUE TITLE
far tick labels drawn when parameter is #false

### ISSUE THREAD

**Issue by bennn** [racket/plot#46]
The docs for `plot-x-far-tick-labels?` etc. say:

> When any of these is #f, the corresponding labels for the ticks on the axis are not drawn. 

But the corresponding labels _are_ drawn if the `plot-x-ticks` parameter (etc.) is overridden.

Example:
```
#lang racket/base
(require plot)
(parameterize* ([plot-x-far-ticks (plot-x-ticks)]
                [plot-y-far-ticks (plot-y-ticks)]
                [plot-x-ticks no-ticks]
                [plot-y-ticks no-ticks]
                [plot-x-far-tick-labels? #false]
                [plot-y-far-tick-labels? #false])
  (plot-pict
    (function values)
    #:x-min 0 #:x-max 2
    #:y-min 0 #:y-max 2))
```

Output:

![plot-far-tick-labels](https://user-images.githubusercontent.com/1731829/44949589-bbe03200-ae02-11e8-94f9-749b841b1ff2.png)

I think the docs are correct and the code should change somehow, maybe to make `plot-x-tick-labels? ` a 3-valued parameter.

**Comment by alex-hhh** [comment]
Hi @bennn , I created a pull request to address this issue, can you have a look at it? Thanks, Alex.

**Comment by bennn** [comment]
https://github.com/racket/plot/commit/9823d1ab9ff9144a8a3114afc0af6a69a0fbc4b7
