### ISSUE TITLE
Minor typo in polar->cartesian function & verification of longitude/latitude proper use.

### ISSUE THREAD

**Issue by encomer** [racket/plot#48]
In the documentation of polar->cartesian function, currently it is writen:

"Converts 2D polar coordinates to 3D cartesian coordinates", but should say 2D.

Also, **please verify** the correctness of the following paragraph after the polar3d function documentation, concerning the ranges of latitudes and longitudes. 

"Currently, latitudes range from 0 to (* 2 pi), and longitudes from (* -1/2 pi) to (* 1/2 pi). These intervals may become optional arguments to polar3d in the future."

Thank you for the excellent plot module.

**Comment by bennn** [comment]
> In the documentation of polar->cartesian function, currently it is writen:
> 
> "Converts 2D polar coordinates to 3D cartesian coordinates", but should say 2D.

Fixed in 13fce6908b68c4b2e4347efd402030c6e6b09d6d

> Also, please verify the correctness of the following paragraph after the polar3d function documentation, concerning the ranges of latitudes and longitudes.
>
> "Currently, latitudes range from 0 to (* 2 pi), and longitudes from (* -1/2 pi) to (* 1/2 pi). These intervals may become optional arguments to polar3d in the future."

Yes, the paragraph is still correct. Here is where the intervals are hard-coded:
https://github.com/racket/plot/blob/master/plot-lib/plot/private/plot3d/isosurface.rkt#L300

**Comment by encomer** [comment]
Thank you @BourgondAries for directing me to the right repository.

And thanks @bennn for fixing the typo. **Still**, I would like to ask you concerning the names of latitudes and longitudes: are they refering to the correct concept? or do we need to swap them? (_I understand that the issue is closed_).

Thanks for all the great work that you are doing.

**Comment by bennn** [comment]
Oh, I see. I'm not familiar with that use, but the docs seem self-consistent and their symbols for latitude/longitude seem to match the definitions here: https://en.wikipedia.org/wiki/Azimuthal_equidistant_projection

**Comment by encomer** [comment]
Thank you @bennn for the reference. Still, please consider checking if in the **polar3d** documentation the term latitude should say longitude and viceversa. 
Extra references: 
[https://msdn.microsoft.com/en-us/library/aa578799.aspx](url)
[https://gisgeography.com/latitude-longitude-coordinates/](url)
_Note_: we can observe that the term latitude have the range (* -1/2 pi) to (* 1/2 pi).

**Comment by bennn** [comment]
I don't see a mistake in the documentation. It looks like different sources have different conventions:

<https://en.wikipedia.org/wiki/Spherical_coordinate_system>
<http://mathworld.wolfram.com/SphericalCoordinates.html>

But lets reopen this as a request to make the latitude/longitude intervals be optional arguments to `polar3d`. Ok?

**Comment by encomer** [comment]
Thank you. The main issue I think, is concerning the _proper user of the terms latitude and longitude_. Thank you again @bennn  for reopen the issue, and for taking the opportunity to review this question. By the way, the optional arguments will be very welcome.

**Comment by bennn** [comment]
Can you explain what you mean by proper use --- or how `polar3d` is improper? It still seems to me that `polar3d` is using the terms in a "standard" way, but there are multiple possible standards.

This page in particular agrees with `polar3d` https://en.wikipedia.org/wiki/Spherical_coordinate_system#Unique_coordinates 
> If it is necessary to define a unique set of spherical coordinates for each point, one must restrict their ranges. A common choice is:
> r ≥ 0
> 0° ≤ θ ≤ 180° (π rad)
> 0° ≤ φ < 360° (2π rad)
> However, the azimuth φ is often restricted to the interval (−180°, +180°], or (−π, +π] in radians, instead of [0, 360°). This is the standard convention for geographic longitude.

**Comment by encomer** [comment]
Thank you @bennn . Please consider the code following this comment: After running it, **my appreciation is that θ is being used as longitude and ρ as latitude**. Thanks in advance for your help to clarify this issue.

_Observation_: the formatting of the code is fine in the Write window, but not in the Preview window. I need to learn how to do it right. _I apologize for that_.


`#lang racket
;;; testingpolar3d.rkt
;;; example adapted from polar3d documentation

(require plot)

(parameterize
    ([plot-decorations?  #t]
     [plot3d-samples     75])
  (define (f1 θ ρ)
    ; nonzero for θ from 0 to pi.
    (if (> θ pi)
        0
        (+ 1 (/ θ 2 pi)
           (* 1/8 (sin (* 8 ρ))))))
  (define (f2 θ ρ)
    ; nonzero for ρ from (* -1/2 pi) to 0.
    (if (> ρ 0)
        0
        (+ 1/2 (/ θ 2 pi)
           (* 1/8 (sin (* 8 ρ))))))
  
  (plot3d
   (list
    (polar3d f1 #:color "cyan"
             #:line-style 'transparent
             #:alpha 2/3)
    (polar3d f2 #:color "navajowhite"
             #:line-style 'transparent
             #:alpha 2/3))
   #:angle 240
   #:altitude 50))

;;; eoc testingpolar3d.rkt`

**Comment by bennn** [comment]
Can you say what you expected and what you see?

This seems like a question of translating the ideas of "latitude" and "longitude" to an X,Y,Z coordinate system. I don't know what's right or wrong for that.

**Comment by encomer** [comment]
Thank you for continue with this issue, and for your question:

What I expected was that θ was used as longitude (as I confirmed in the generated figure). On the other hand, ρ was used as latitude, as I expected. So, it seems to me, that **the terms longitude and latitude (in the polar3d documentation) are used not consistent with the functional result**, which is the correct and expected one.

Thank you again @bennn  for your patience.

**Comment by bennn** [comment]
What does "used as longitude" mean on an X,Y,Z coordinate system?

**Comment by bennn** [comment]
> On Figure 1 (based on an XYZ cartesian coordinate system)

For reference: 
![screen shot 2018-11-09 at 08 34 51](https://user-images.githubusercontent.com/1731829/48265297-2bbdfa80-e3fa-11e8-9367-2a5502822f85.png)

> longitude is denoted by the symbol λ

So in Figure 1, longitudes are plotted along the X and Y axes

> and latitude by the symbol ϕ. 

and latitudes are plotted along the Z axis.


Whereas in plot's `polar3d`, it looks like latitudes are plotted along the X and Y axes and longitudes are plotted along the Z.

That does seem like a bug in `polar3d`

**Comment by encomer** [comment]
Thanks @bennn. It seems to me that **the functionality of polar3d is all right**. _It's only in the way the document use the latitude and longitude terms_. That is, longitude should be (it seems to me) associated with θ, and latitude should be associated with ρ.

There is a difference of the symbol θ usage in physics and mathematics. **We are using the mathematics convention**, as described in the previously referred link: [Spherical_coordinate_system](url) (see 2nd Figure). In the mentioned figure, the spherical coordinates are specified as (r, θ, ϕ), whereas in polar3d, the specification is in terms of (r, θ, ρ), which is ok, considering ϕ+ρ=pi/2.

_Note_: it would be very helpful, to have the opinion of the original developers of polar3d, just in case we are missing something. Thank you again for your support.

**Comment by bennn** [comment]
#56 associates longitude with θ and latitude with the other variable

Thank you @encomer for your many comments & patience in this issue

**Comment by encomer** [comment]
Hello Ben:

Thank you very much for the good news of your email and also for your patience with me. 
Congratulations for all the excellent work that you do in the Racket development team.

Sincerely,E. Cómer (cemati.org, ITT)
P.S. One functionality that would be great in Plot, is to be able to incluye LaTeX code in the Title of a Plot, or for the different labels. Currently the only acceptable type is a string, but it would be nice to allow LaTeX, in the same way that Scribble (using scribble-math) allows to write, for example @${\dfrac{dy}{dx}}. Thank you again for all your support.


    On Tuesday, September 3, 2019, 08:40:43 PM PDT, Ben Greenman <notifications@github.com> wrote:  
 
 
#56 associates longitude with θ and latitude with the other variable

Thank you @encomer for your many comments & patience in this issue
