### ISSUE TITLE
Square pen cap for decorations

### ISSUE THREAD

**Issue by bennn** [racket/plot#6]
(edited 2020-07-03)

Currently, every line on a plot gets drawn with a round pen. This isn't always the right look. I might want tick marks to be squared off. (See crayon-drawing feeling in #48.)

Feature request: add parameters to choose the `pen-cap-style/c`. The "decorations" pen should be independent from the main "renderers" pen if possible.

- - -

(original issue)
Make sure that
- extra axes
- plot boundaries
- tick lines
- (other decorations)

are all drawn with the `'butt` pen cap.

Also, add helpers to make hrule and vrule lines.

**Comment by spdegabrielle** [comment]
is this still an issue?  Please consider adding the label `good first issue` so it is findable: 

[Issues labeled `good first issue` in in Racket GitHub repositories](https://github.com/search?q=type:issue+org:racket+state:open+label:%22good+first+issue%22)

**Comment by spdegabrielle** [comment]
Hi @bennn is this still an issue?

**Comment by alex-hhh** [comment]
Actually, my question is why is this an issue?  Is there a problem with the way they are drawn now?  Would this fix #8?

**Comment by bennn** [comment]
I think I was thinking that a square pen would look better for ticks, etc.

Now, I'd rather have a parameter to choose the pen cap. I'll update the issue title/description.

This would not fix #8. It might help for lines that are square to the x/y axis, but not for anything else.
