### ISSUE TITLE
Inverting axis transforms

### ISSUE THREAD

**Issue by dented42** [racket/plot#84]
For completeness it seems like the following functions for reversing axis transforms should exist:
```
;;; Turn an axis transform inside out
(: axis-transform-invert (Axis-Transform -> Axis-Transform))

;;; apply an axis transform in reverse
(: apply-axis-transform/reverse (Axis-Transform Real Real -> Invertible-Function))
```

**Comment by alex-hhh** [comment]
I am not sure how any of these functions would be implemented, but if you provide an implementation as a pull request, I am happy to review it and help you with getting it ready for merging (documentation , tests, etc).

Also, would you be able to provide some example use cases for these functions?

**Comment by alex-hhh** [comment]
Hi @dented42 , with reference to my previous message,  can you please:

* provide some examples where the functions would be useful
* provide an explanation on how these functions would be implemented?  A sample Racket implementation would be great.

If you consider providing a pull request, I can help you with getting it ready for merging (documentation , tests, etc).  This is not necessary, but I cannot see how these functions can be implemented, so I cannot do anything about this issue.

**Comment by dented42** [comment]
What made me think of it initially was mostly that axis transforms (If I'm understanding the implementation correctly) seem to be made of invertible functions, and it seems aesthetically odd that the invertibility isn't exposed for completeness.

The specific example I had in mind was wanting an exponential transform, and inverting the log transform seemed like the most straightforward way.

I'll try to whip up an implementation when I'm able.

**Comment by dented42** [comment]
(Just noticed I mucked up one of the signatures in my initial post, I've corrected it)

**Comment by dented42** [comment]
Another more pressing example that has come up is actually trying to integrate `plot` into a GUI (I've been playing with `lux` lately), and wanting to translate mouse/window coordinates back into plot coordinates. Besides using `lux` it also just seems useful to be able to draw a plot into a graphics context and be able to map back and forth between canvas coordinates and the coordinate system defined in the plot. Obviously the axis transform is only a single part of that equation, but it seems like an important part as it's the part that introduces nonlinearity.

**Comment by alex-hhh** [comment]
The functionality you requested in #83 is already available for plot snips, where the coordinates passed back to the callback are converted back to plot coordinates, and this works in the presence of axis transforms.  So these functions are not needed to implement such functionality.

Also, #83 is about how to expose already existing functionality to the other plot entry points (such as `plot/dc` and related functions), which are designed for non-interactive use.  As you see from that discussion, the design of that API is not easy...

You can already implement interactive plots where mouse coordinates are converted to plot coordinates and you can draw additional things on the plot interactively, except you need to use plot snips and the Racket GUI library for that.

**Comment by dented42** [comment]
Given that this suggestion was based on a misunderstanding of how best to accomplish #83, I can no longer think of an actual practical use case for this feature request. I'm going close this issue as 'it seems kinda nifty but I can't say why exactly' isn't exactly rock the best argument for implementing something. If anyone can think of any reasons why this should exist and would be useful feel free to re-open it or re-file or whatever the accepted etiquette is here.
