### ISSUE TITLE
Support Interactive Overlays in Standalone Frames

### ISSUE THREAD

**Issue by nick-chandoke** [racket/plot#98]
`plot-frame` currently accepts only a renderer tree. it should also accept a snip, so that we can have interactive overlays in standalone frames.

while we're at it, we may as well allow the user to specify the frame title (without the "Plot: " prefix) and border width(s) as parameters.

**Comment by alex-hhh** [comment]
You can both set interactive overlays and set custom titles to plot frames.  

The plot title is the easiest, all you have to do is call `set-label` on the plot frame:

```racket
#lang racket
(require plot)
(define frame (plot-frame (function sin -5 5)))
(send frame show #t)
(send frame set-label "A Custom Plot Title")
```

To set an overlay renderer is a bit more complicated, you have to get the snip out of the plot frame, but this is created sometimes after the frame is show.  The simplest thing is to wait in a loop for it to be created:

```racket
#lang racket
(require plot racket/gui)
(define frame (plot-frame (function sin -5 5)))
(send frame show #t) ;; Frame MUST be show, otherwise we loop forever 

(define snip
  (let loop ()
    (define snip
      (let ([c (first (send frame get-children))])
        (send c get-snip)))
    (or snip
        (begin
          (sleep/yield 0.1)
          (loop)))))

(send snip set-mouse-event-callback
      (lambda (snip event x y)
        (when x
          (send snip set-overlay-renderers (vrule x)))))
```

You can combine both of these techniques into your own custom function.  As an alternative you can use [snip-canvas%](https://docs.racket-lang.org/mrlib/snip.html?q=snip-canvas%25#%28def._%28%28lib._mrlib%2Fsnip-canvas..rkt%29._snip-canvas~25%29%29) to add a plot snip to a frame

**Comment by alex-hhh** [comment]
I hope my previous message answered your question, so I will close this issue.  

For other questions about the plot package or Racket in general, I recommend posting on the [racket-users](https://groups.google.com/g/racket-users) list or on the Racket [slack channel](https://racket.slack.com/) (you can sign up for Slack [here](https://racket-slack.herokuapp.com/))
